#
#
#

STRING(TOUPPER "${CMAKE_BUILD_TYPE}" _build_type)

if("${_build_type}" STREQUAL "DEBUG")

    set(CMAKE_SHARED_LIBRARY_SUFFIX "-debug${CMAKE_SHARED_LIBRARY_SUFFIX}")
    set(CMAKE_STATIC_LIBRARY_SUFFIX "-debug${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_EXECUTABLE_SUFFIX     "-debug${CMAKE_EXECUTABLE_SUFFIX}")

elseif("${_build_type}" STREQUAL "RELWITHDEBINFO")

    set(CMAKE_SHARED_LIBRARY_SUFFIX "-rdebug${CMAKE_SHARED_LIBRARY_SUFFIX}")
    set(CMAKE_STATIC_LIBRARY_SUFFIX "-rdebug${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_EXECUTABLE_SUFFIX     "-rdebug${CMAKE_EXECUTABLE_SUFFIX}")

elseif("${_build_type}" STREQUAL "MINSIZEREL")

    set(CMAKE_SHARED_LIBRARY_SUFFIX "-minsize${CMAKE_SHARED_LIBRARY_SUFFIX}")
    set(CMAKE_STATIC_LIBRARY_SUFFIX "-minsize${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_EXECUTABLE_SUFFIX     "-minsize${CMAKE_EXECUTABLE_SUFFIX}")

endif()

unset(_build_type)

