#
#
#

STRING(TOUPPER "${CMAKE_BUILD_TYPE}" _build_type)

if("${_build_type}" STREQUAL "DEBUG")

    set(CMAKE_SHARED_LIBRARY_SUFFIX "-d${CMAKE_SHARED_LIBRARY_SUFFIX}")
    set(CMAKE_STATIC_LIBRARY_SUFFIX "-d${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_EXECUTABLE_SUFFIX     "-d${CMAKE_EXECUTABLE_SUFFIX}")

elseif("${_build_type}" STREQUAL "RELWITHDEBINFO")

    set(CMAKE_SHARED_LIBRARY_SUFFIX "-rd${CMAKE_SHARED_LIBRARY_SUFFIX}")
    set(CMAKE_STATIC_LIBRARY_SUFFIX "-rd${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_EXECUTABLE_SUFFIX     "-rd${CMAKE_EXECUTABLE_SUFFIX}")

elseif("${_build_type}" STREQUAL "MINSIZEREL")

    set(CMAKE_SHARED_LIBRARY_SUFFIX "-ms${CMAKE_SHARED_LIBRARY_SUFFIX}")
    set(CMAKE_STATIC_LIBRARY_SUFFIX "-ms${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_EXECUTABLE_SUFFIX     "-ms${CMAKE_EXECUTABLE_SUFFIX}")

endif()

unset(_build_type)

